version: '3.6'
services:
  kestrel:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-alpine
    command: sh -c "apk update && apk --no-cache add gcompat && apk --no-cache add protobuf && dotnet build && dotnet run"
    working_dir: /app/FlowControlTest.Server.Kestrel/
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
  core:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-alpine
    command: sh -c "apk update && apk --no-cache add gcompat && apk --no-cache add protobuf && dotnet build && dotnet run"
    working_dir: /app/FlowControlTest.Server.Core/
    ports:
      - "5001:5001"
    volumes:
      - .:/app/
